### ISSUE TITLE
multiple app bugs

### ISSUE THREAD

**Issue by soundsnow** [fireclouu/spaceinvaders_androidport#1]
open this app in portrait mode, then landscape mode, it's black screen or crashed
open another app (Android's Settings app) in landscape mode, recent views, Space Invaders, it's displayed but filled screen

The text in the corners is too small to read, are they necessary?
This app should not have an Invader icon? it's an Android icon!
![Screenshot_20240617-191904_Space Invaders](https://github.com/fireclouu/space_invaders_intel_8080_emu/assets/109885044/a895b09d-4463-45f5-b9f5-fc5b9afa6c06)

**Comment by fireclouu** [comment]
Hi! thanks for the tip! I'll address this issue as soon as possible.

So far I'm still working on optimizing VRAM presentation onto android SurfaceView, and decoupling parts of the code for better portability.

**Comment by soundsnow** [comment]
By the Way, I added this emulator to [GCA3A](https://emulation.gametechwiki.com/index.php/GCA3A), it took me six months to create it, although the author's name on the page is kyo2adr raburi

**Comment by fireclouu** [comment]
Hi! I just push commits fixing some of issues above. It also utilizes hardware features for better performance. Please check action builds for now  Thanks!

About those texts below you mentioned, its just for logs and emulator infos. It will be separated on next commits.

**Comment by soundsnow** [comment]
GitHub Actions is not a good idea, you have to have an account to download it and after three months it expires and you can no longer download it. I know some people will re-edit their android.yml or build.yml or release.yml. each build automatically replaces Releases latest tag and it doesn't generate more tags. this yml file is not so good, it's a debug not a release, doesn't have a good signature, and each time you update you have to uninstall the old version. the apk file is inside the zip file, you have to unzip it with an app like ZArchiver every time you download it.
The latest version of the apk generated by GitHub Actions is automatically released and replaces the old one.

**Comment by fireclouu** [comment]
I'll add CI for release build stubs later on, for now I'm focusing on improving stability and functionality of the emulator. I will add release version tonight. Please test it, I've added more functionalities and 2 Player modes with these recent build.

I will also close this now as issues has been fixed.
