### ISSUE TITLE
bug: P2 and Landscape

### ISSUE THREAD

**Issue by soundsnow** [fireclouu/spaceinvaders_androidport#2]
Unable to pause and resume the game
P2 is unable to Start and Coin
Switching between Portrait and Landscape restarts the game and game progress disappears
P1 P2 button blocked the invaders

Android 13 AOSP has a pure black theme turned on and the icons seem to be pure black when the apk is installed. It doesn't matter, it shows normal colors after installation
Android 13 monochrome or theme icons. Icons will automatically change to your favorite color. app/src/main/strings/values/color.xml? add Add what starts with monochrome
![Screenshot_20240625-113939_Space Invaders](https://github.com/fireclouu/space_invaders_intel_8080_emu/assets/109885044/5a3354c6-c9aa-445c-968b-d3f7e4708328)

**Comment by fireclouu** [comment]
Hi again! Thanks for your contribution.

I just released fixes for these recently, please tell me if it is okay on your end.

Also regarding to issue with app icons, current one has transparent png format. It can be fixed quite easily but Ill stick to emulation issues as main priority. I also encourage everyone to open pull request whenever possible. Thanks!

**Comment by fireclouu** [comment]
I just forgot to mention those restarts when orientation changes. Currently working on these one. Expect to be fixed on next commit.

**Comment by fireclouu** [comment]
Hi!

[alpha-0.5](https://github.com/fireclouu/space_invaders_intel_8080_emu/releases/tag/alpha-0.5) hopes to fix this issues. Thanks for reporting!
